language: ruby
sudo: false
rvm:
  - 2.3.0

node_js:
  - "6"
sudo: false
cache:
  - node_modules
  - bundler
  
before_install:
  - openssl aes-256-cbc -K $encrypted_4a5f4ffc7c9a_key -iv $encrypted_4a5f4ffc7c9a_iv -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - npm install -g webpack

global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - chmod +x deploy.sh
  - bash ./deploy.sh 

# whitelist
branches:
  only:
    - master

# http://simpleit.rocks/automated-deployment-of-jekyll-websites-to-github-pages-with-a-git-push-to-github/
# WARNING: travis encrypt appears to be broken on Windows.  Had to use Non-Windows system for it to decrypt properly

# STEPS
# go to https://travis-ci.org and enable you repository
# check only build when there is a .travis.yml file and uncheck pull request
# ssh-keygen -t rsa -b 4096 -C "your_github_email@example.com" -f "id_rsa"
# no pass phrase
# clip < tsdeploy.rsa.pub
# Add the key as a deploy key to the github repository with write access
# install travis command line: gem install travis
# On a non-Windows system run travis encrypt-file id_rsa
# at travis-ci.org if you go the settings for the repository, you should now also see two environment variables that match the names in the openssl command
# update .travis.yml before_install section with the openssl command from the travis encrypt-file output
# make sure to remove the id_rsa and id_rsa.pub
# add the id_rsa.enc to github
