# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TypeScript A Day
email: hello@typescriptaday.com
description: > # this means to ignore newlines until "baseurl:"
  TypeScript A Day provides training courses to help you level up on
  the TypeScript language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://typescriptaday.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: typescriptaday
github_username:  typescriptaday

# Build settings
markdown: kramdown
theme: minima
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - deploy.sh
  - node_modules
  - id_rsa.enc
  - .gitignore
  - yarn.lock
  - package.json
  
sass:
  sass_dir: _scss
